name: Révision de code

on:
  pull_request

# on:
#   pull_request:
#     types: [opened, edited, reopened, synchronize]
jobs:
  validation-pullrequest:
    name: Validation de pullrequest
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # inclure l'history de deux commit
          submodules: true
      # - run : git checkout ${{ github.event.pull_request.head.sha }} 
      - name: Find linked issues
        uses: nearform-actions/github-action-check-linked-issues@v1.4
        id: check-linked-issues
        with:
          exclude-branches: "main"
      - name : update scripts 
        shell: pwsh
        run : |
          git config --global user.name "ESSARRAJ"
          git config --global user.email "essarraj.fouad@gmail.com"
          git submodule update --remote
      - name : run echo github.event.pull_request.changed_files
        run : echo ${{github.event.pull_request.changed_files}}
      - name: run code-review.ps1
        shell: pwsh
        run: ./scripts/code-review/code-review.ps1 "${{ github.event.pull_request.title }}" ${{github.event.pull_request.commits}} ${{ steps.check-linked-issues.outputs.issues }}
        env:
          GH_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}